### PR TITLE
Merge spec file from git

### PR DESCRIPTION
**Pull request by lnussel**

### CODE REVIEW

**Comment by lnussel** [comment]
created using this:
```
package=microos-tools
git clone https://gitea.opensuse.org/rpm/$package
cd $package
git filter-repo --path $package.spec --force
git rebase `git rev-list HEAD|tail -1`
cd ..
git fetch $package
git merge FETCH_HEAD --allow-unrelated-histories
```

**Comment by Vogtinator** [comment]
IMO this should just be a single commit which adds the .spec file. The history is only useful in combination with the rest of the repo at that point.

**Comment by lnussel** [comment]
added without history

**Comment by lnussel** [comment]
spec file still unchanged since then so should be ok to merge

**Pull request merged**
